export const BREAKPOINTS = {
  XS: 'xs',
  SM: 'sm',
  MD: 'md',
  LG: 'lg',
  XL: 'xl',
  XXL: 'xxl',
};

export const BREAKPOINT_COLS = {
  [BREAKPOINTS.XS]: 2,
  [BREAKPOINTS.SM]: 2,
  [BREAKPOINTS.MD]: 3,
  [BREAKPOINTS.LG]: 4,
  [BREAKPOINTS.XL]: 6,
  [BREAKPOINTS.XXL]: 6,
};

export const publishers = {
  MARVEL: [
    'Angel',
    'Angel Salvadore',
    'Ant-Man',
    'Anti-Venom',
    'Anti-Vision',
    'Archangel',
    'Binary',
    'Deadpool',
    'Evil Deadpool',
    'Gemini V',
    'Giant-Man',
    'Goliath',
    'Iron Lad',
    'Jean Grey',
    'Marvel Comics',
    'Meltdown',
    'Ms Marvel II',
    'Phoenix',
    'Power Man',
    'Power Woman',
    'Rebellion',
    'Rune King Thor',
    'Scorpion',
    'She-Thing',
    'Speed Demon',
    'Spider-Carnage',
    'Tempest',
    'Thunderbird II',
    'Toxin',
    'Venom III',
    'Vindicator II',
  ],
  DC: [
    'Aztar',
    'Batgirl',
    'Batgirl III',
    'Batgirl V',
    'Batman II',
    'Black Racer',
    'Boom-Boom',
    'DC Comics',
    'Impulse',
    'Oracle',
    'Nightwing',
    'Red Hood',
    'Red Robin',
    'Robin II',
    'Robin III',
    'Superman Prime One-Million',
  ],
};
