export const publishers = {
  MARVEL: [
    'Angel',
    'Angel Salvadore',
    'Ant-Man',
    'Anti-Venom',
    'Anti-Vision',
    'Archangel',
    'Binary',
    'Deadpool',
    'Evil Deadpool',
    'Gemini V',
    'Giant-Man',
    'Goliath',
    'Iron Lad',
    'Jean Grey',
    'Marvel Comics',
    'Meltdown',
    'Ms Marvel II',
    'Oracle',
    'Phoenix',
    'Power Man',
    'Power Woman',
    'Rebellion',
    'Rune King Thor',
    'Scorpion',
    'She-Thing',
    'Speed Demon',
    'Spider-Carnage',
    'Tempest',
    'Thunderbird II',
    'Toxin',
    'Venom III',
    'Vindicator II',
  ],
  DC: [
    'Aztar',
    'Batgirl',
    'Batgirl III',
    'Batgirl V',
    'Batman II',
    'Black Racer',
    'Boom-Boom',
    'DC Comics',
    'Impulse',
    'Nightwing',
    'Red Hood',
    'Red Robin',
    'Robin II',
    'Robin III',
    'Superman Prime One-Million',
  ],
};
